##########################
# Input files (required) #
##########################

sample_fastqs:
  example:
    # Read 1 (16bp Visium barcode + 12bm UMI)
    R1: data/example_r1.fastq.gz
    # Read 2 (gDNA only)
    R2: data/example_r2.fastq.gz

sample_alignment_jsons:
  # Path to SpaceRanger fiducial alignment json - if you want to do automated alignment (currently not implemented), put 'none' 
  example: data/example.json

# Path and prefix for bowtie2 genome reference
ref: refs/GrCm39/GrCm39

#########################
# Configuration options #
#########################

# Path for text file containing barcode whitelist
whitelist: refs/visium-v1.txt

# Path for text file containing spatial row/column indices of valid barcodes
spot_coords: refs/visium-v1_coordinates.txt

# Whether to use UMIs for deduplication
umi_dedup: False

### Options for MACS2 peak calling
# FDR threshold for peak calling
macs2_fdr: 0.01

# Effective genome size
# Defaults for species:
#   hs: 2.7e9
#   mm: 1.87e9
#   ce: 9e7
#   dm: 1.2e8
macs2_genomesize: 1.87e9